version: 2.1
orbs:
  go: circleci/go@1.3.0
  jq: circleci/jq@2.1.0

references:

commands:
  publish_terraform_output:
    parameters:
      input-file:
        type: string
    steps:
      - run:
          name: publish terraform output
          command: |
            if [ $(cat /tmp/pr-response | jq length) -eq 0 ]; then
              echo "No PR found to update"
            else
              pr_comment_url=$(cat /tmp/pr-response | jq -r ".[0]._links.comments.href")

              # get the TF plan output (from the workspace)
              # 1. escape the double quotes
              # 2. add a \n at the end of each line
              # 3. delete non-ascii chars
              # 3. delete the empty lines
              pr_comment=$(cat << parameters.input-file >> | \
                sed 's/"/\\\"/g' | \
                sed 's/$/\\n/g' | \
                tr -d '\200-\377' | \
                tr -d '\n')

              codeblock='```'
              pr_comment_json="{ \"body\": \"${codeblock}\n${pr_comment}\n${codeblock}\" }"

              echo "JSON: ${pr_comment_json}"

              curl --location --request POST "${pr_comment_url}" \
                -u $GH_USER:$GITHUB_TOKEN \
                --header 'Content-Type: application/json' \
                --data-binary "${pr_comment_json}" \
                --trace ~/moo.out

                cat ~/moo.out
            fi

working_directory: &working_directory
  ~/project

bin_directory: &bin_directory
  ~/bin

python_image: &python_image
  circleci/python:latest

default_config: &default_config
  docker:
    - image: *python_image
  working_directory: *working_directory
  environment:
    BASH_ENV: ~/.bashrc
    TERRAFORM_ENV: ~/project/
    TF_IN_AUTOMATION: true

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to restore repository from cache
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory
      - *bin_directory

set_terraform_environment: &set_terraform_environment
  run:
    name: set terraform environment
    command: |
      echo $PATH
      touch .bashrc
      cd ~/project/

terraform_install: &terraform_install
  run:
    name: install terraform
    command: |
      wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      sudo unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d ~/bin
      rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      terraform --version

tfnotify_install: &tfnotify_install
  run:
    name: install tfnotify
    command: |
      wget https://github.com/mercari/tfnotify/releases/download/v0.6.2/tfnotify_linux_amd64.tar.gz
      sudo tar -xf tfnotify_linux_amd64.tar.gz -C ~/bin

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      terraform init -backend-config="token=${TF_API_TOKEN}"

apply_job: &apply_job
  <<: *default_config
  steps:
    - *restore_repo
    - *set_terraform_environment
    - attach_workspace:
        at: *working_directory
    - run:
        name: terraform apply
        command: |
          terraform apply --auto-approve -no-color | tee /tmp/terraform-output
    - persist_to_workspace: # save the TF plan output to the workspace for updating a PR
        root: /tmp
        paths:
          - terraform-output

jobs:

  build:
    <<: *default_config
    steps:
      - checkout
      - *terraform_install
      - *set_terraform_environment
      - *terraform_init
      - run:
          name: terraform fmt
          command: |
            terraform fmt
      - *save_repo

  plan:
#    docker: [{ image: "circleci/golang:latest" }]
#    working_directory: "~/project"
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_environment
      - *tfnotify_install
      - run:
          name: terraform plan
          command: |
            # terraform plan -input=false -no-color -out=/tmp/terraform-plan-outfile | tee /tmp/terraform-output
            terraform plan -input=false -no-color -out=/tmp/terraform-plan-outfile | tfnotify --config tfnotify_config.yml plan
      - persist_to_workspace: # save the TF plan output to the workspace for updating a PR
          root: /tmp
          paths:
            - terraform-plan-outfile
              # - terraform-output

  apply:
    <<: *apply_job
  apply-with-approval:
    <<: *apply_job

  compliance_test:
    <<: *default_config
    steps:
      - attach_workspace:
          at: /tmp
      - *restore_repo
      - *set_terraform_environment
      - run:
          name: terraform-compliance tests
          command: |
            pip install terraform-compliance

            # terraform seems to only be able to use the plugins when the plan file is local to the .terraform dir
            cp /tmp/terraform-plan-outfile .
            # perl command strips out color coding
            terraform-compliance -f compliance-tests/ -p terraform-plan-outfile | perl -pe 's/\x1b\[[0-9;]*[mG]//g' | tee /tmp/terraform-compliance-test-output
      - publish_terraform_output:
          input-file: /tmp/terraform-compliance-test-output

  update_open_pr:
    <<: *default_config
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: get open pr url
          command: |
            curl --location --request GET "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH&state=open&sort=updated&direction=desc" \
              -u $GH_USER:$GITHUB_TOKEN > /tmp/pr-response
#      - publish_terraform_output:
#          input-file: /tmp/terraform-output
      - persist_to_workspace: # save the url for the open PR
          root: /tmp
          paths:
            - pr-response

  update_closed_pr:
    <<: *default_config
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: get closed pr url
          command: |
            curl --location --request GET "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?state=closed&sort=updated&direction=desc" \
              -u $GH_USER:$GITHUB_TOKEN > /tmp/pr-response
      - publish_terraform_output:
          input-file: /tmp/terraform-output

  deployment:
    docker: [{ image: "circleci/python:latest" }]
    working_directory: "~/project"

    steps:
      - run:
          name: "Push to S3"
          command: |
            pip install --user awscli
            export PATH="~/.local/bin:$PATH"
            git clone https://github.com/hashicorp/learn-terraform-circleci/ .
            aws s3 sync --acl public-read "/home/circleci/project/assets" s3://${APP_BUCKET}

  destroy:
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_environment
      - run:
          name: "Destruction of env"
          command: |
            terraform destroy --auto-approve

workflows:
  version: 2
  build_plan_approve_apply:
    jobs:
      - build
      - plan:
          context: learn-circle-staging
          requires:
            - build
      - update_open_pr:
          requires:
            - plan
      - compliance_test:
          requires:
            - update_open_pr
#      - apply:
#          context: learn-circle-staging
#          requires:
#            - plan
#      - deployment:
#          requires:
#            - apply
#      - hold:
#          type: approval
#          requires:
#            - deployment
#      - destroy:
#          requires:
#            - hold
#
